FROM ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main

# Install Python and tools (adjust versions as needed)
RUN apt-get update && apt-get install -y python3 python3-pip
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install build setuptools setuptools-rust wheel
