[target.arm-unknown-linux-gnueabihf]
image = "fluvio-cross-python:arm-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
image = "fluvio-cross-python:armv7-unknown-linux-gnueabihf"

[target.aarch64-unknown-linux-gnu]
image = "fluvio-cross-python:aarch64-unknown-linux-gnu"
