name: Fluvio Cloud CI

concurrency:
  group: cloud-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 14 * * *"

jobs:
  smoke_test:
    name: Smoke test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
        python-version: ["3.9", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            target/
          key: ${{ matrix.os }}-cargo-${{matrix.python-version}}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install rust ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install fluvio
        run: |
          curl -fsS https://hub.infinyon.cloud/install/install.sh | bash
          echo "${HOME}/.fluvio/bin" >> $GITHUB_PATH

      - name: Login to fluvio cloud
        run: |
          fluvio cloud login --email ${CLOUD_USER_EMAIL} --password ${CLOUD_USER_PASSWORD} --remote 'https://dev.infinyon.cloud'
          # add profile
          fluvio cloud cluster sync
        env:
          CLOUD_USER_EMAIL: ${{ secrets.ORG_CLOUD_SERVICE_EMAIL }}
          CLOUD_USER_PASSWORD: ${{ secrets.ORG_CLOUD_SERVICE_PASSWD_DEV }}

      - name: Unit Tests
        env:
          FLV_SOCKET_WAIT: 300
        run: |
          make unit-tests
      - name: Run Integration Tests
        run: |
          make integration-tests
        env:
          FLV_SOCKET_WAIT: 300

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
